# Generated by Django 3.2.20 on 2023-09-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_has_sizes_product_has_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_size',
            new_name='has_sizes',
        ),
    ]
